project:
  type: website

website:
  title: "Shairam Manickaraj"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
